//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foreclosures
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int ListingID { get; set; }
        public string ListingAddress { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string Image { get; set; }
        public string Price { get; set; }
        public Nullable<bool> BeenRemoved { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string ScopeOfWork { get; set; }
        public string PDFLink { get; set; }
        public Nullable<double> zipcode { get; set; }
        public Nullable<int> cityId { get; set; }
        public string additionalInfo { get; set; }
        public string propertyType { get; set; }
        public string bedrooms { get; set; }
        public string baths { get; set; }
        public Nullable<int> typeId { get; set; }
        public string saleDate { get; set; }
    
        public virtual County County { get; set; }
        public virtual CountyListingType CountyListingType { get; set; }
    }
}
