//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foreclosures
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ForeclosuresEntities : DbContext
    {
        public ForeclosuresEntities()
            : base("name=ForeclosuresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Listing> Listings { get; set; }
    
        public virtual int Batch_Listing_Delete(Nullable<int> countyID)
        {
            var countyIDParameter = countyID.HasValue ?
                new ObjectParameter("CountyID", countyID) :
                new ObjectParameter("CountyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Batch_Listing_Delete", countyIDParameter);
        }
    
        public virtual int Mark_All_As_Removed(Nullable<int> countyID)
        {
            var countyIDParameter = countyID.HasValue ?
                new ObjectParameter("CountyID", countyID) :
                new ObjectParameter("CountyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Mark_All_As_Removed", countyIDParameter);
        }
    }
}
