//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foreclosures
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polygon
    {
        public int polygonId { get; set; }
        public string polygonName { get; set; }
        public string northwestAddress { get; set; }
        public string northeastAddress { get; set; }
        public string southeastAddress { get; set; }
        public string southwestAddress { get; set; }
        public string northwestCoord { get; set; }
        public string northeastCoord { get; set; }
        public string southeastCoord { get; set; }
        public string southwestCoord { get; set; }
        public Nullable<int> countyId { get; set; }
        public Nullable<int> cityId { get; set; }
    }
}
